// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: api/proto/shortener.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRegisterRequest запрос на регистрацию пользователя
type UserRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login  string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`   // имя пользователя
	Secret string `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"` // пароль
}

func (x *UserRegisterRequest) Reset() {
	*x = UserRegisterRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterRequest) ProtoMessage() {}

func (x *UserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserRegisterRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// UserRegisterResponse результат регистрации пользователя
type UserRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // токен верификации для подстановки в запросы
}

func (x *UserRegisterResponse) Reset() {
	*x = UserRegisterResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterResponse) ProtoMessage() {}

func (x *UserRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterResponse.ProtoReflect.Descriptor instead.
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ------------- авторизация пользователя-----------------------------
// UserAuthRequest запрос на верификацию пользователя
type UserAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login  string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`   // логин клиента
	Secret string `protobuf:"bytes,2,opt,name=Secret,proto3" json:"Secret,omitempty"` // пароль
}

func (x *UserAuthRequest) Reset() {
	*x = UserAuthRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthRequest) ProtoMessage() {}

func (x *UserAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthRequest.ProtoReflect.Descriptor instead.
func (*UserAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *UserAuthRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserAuthRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// UserAuthResponse результат верификации пользователя
type UserAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // токен верификации для подстановки в запросы
}

func (x *UserAuthResponse) Reset() {
	*x = UserAuthResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthResponse) ProtoMessage() {}

func (x *UserAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthResponse.ProtoReflect.Descriptor instead.
func (*UserAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *UserAuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// -------------- сокращение одной ссылки ----------------------------
// EncodeLinkRequest запрос на получение сокращенной ссылки для одного адреса
type EncodeLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=OriginalUrl,proto3" json:"OriginalUrl,omitempty"` // исходная ссылка для сокращения
}

func (x *EncodeLinkRequest) Reset() {
	*x = EncodeLinkRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeLinkRequest) ProtoMessage() {}

func (x *EncodeLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeLinkRequest.ProtoReflect.Descriptor instead.
func (*EncodeLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *EncodeLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// EncodeLinkResponse ответ с результатом получения ссылки для одного адреса
type EncodeLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortLink string `protobuf:"bytes,1,opt,name=ShortLink,proto3" json:"ShortLink,omitempty"` // короткая ссылка для полученного адреса
}

func (x *EncodeLinkResponse) Reset() {
	*x = EncodeLinkResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeLinkResponse) ProtoMessage() {}

func (x *EncodeLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeLinkResponse.ProtoReflect.Descriptor instead.
func (*EncodeLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *EncodeLinkResponse) GetShortLink() string {
	if x != nil {
		return x.ShortLink
	}
	return ""
}

// ---------------- сокращение пакета ссылок --------------------------
// EncodeBatchLinksRequest запрос на пакетное сокращение ссылок
type EncodeBatchLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*EncodeBatchLinksRequestEntity `protobuf:"bytes,1,rep,name=Links,proto3" json:"Links,omitempty"` // массив с данными для сокращения
}

func (x *EncodeBatchLinksRequest) Reset() {
	*x = EncodeBatchLinksRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeBatchLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeBatchLinksRequest) ProtoMessage() {}

func (x *EncodeBatchLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeBatchLinksRequest.ProtoReflect.Descriptor instead.
func (*EncodeBatchLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *EncodeBatchLinksRequest) GetLinks() []*EncodeBatchLinksRequestEntity {
	if x != nil {
		return x.Links
	}
	return nil
}

// EncodeBatchLinksEntity данные одной ссылки в пакетном запросе на сокращение
type EncodeBatchLinksRequestEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID string `protobuf:"bytes,1,opt,name=CorrelationID,proto3" json:"CorrelationID,omitempty"` // идентификатор ссылки
	OriginalURL   string `protobuf:"bytes,2,opt,name=OriginalURL,proto3" json:"OriginalURL,omitempty"`     // оригинальный url
}

func (x *EncodeBatchLinksRequestEntity) Reset() {
	*x = EncodeBatchLinksRequestEntity{}
	mi := &file_api_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeBatchLinksRequestEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeBatchLinksRequestEntity) ProtoMessage() {}

func (x *EncodeBatchLinksRequestEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeBatchLinksRequestEntity.ProtoReflect.Descriptor instead.
func (*EncodeBatchLinksRequestEntity) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *EncodeBatchLinksRequestEntity) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *EncodeBatchLinksRequestEntity) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

// EncodeBatchLinksResponse ответ с результатом пакетного сокращения ссылок
type EncodeBatchLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link []*EncodeBatchLinksResponseEntity `protobuf:"bytes,1,rep,name=Link,proto3" json:"Link,omitempty"` // массив с результатом сокращения ссылок
}

func (x *EncodeBatchLinksResponse) Reset() {
	*x = EncodeBatchLinksResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeBatchLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeBatchLinksResponse) ProtoMessage() {}

func (x *EncodeBatchLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeBatchLinksResponse.ProtoReflect.Descriptor instead.
func (*EncodeBatchLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *EncodeBatchLinksResponse) GetLink() []*EncodeBatchLinksResponseEntity {
	if x != nil {
		return x.Link
	}
	return nil
}

// EncodeBatchLinksResponseEntity данные по одной ссылке в ответе на пакетное сокращение
type EncodeBatchLinksResponseEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationID string `protobuf:"bytes,1,opt,name=CorrelationID,proto3" json:"CorrelationID,omitempty"` // идентификатор ссылки
	ShortURL      string `protobuf:"bytes,2,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`           // сокращенный урл
}

func (x *EncodeBatchLinksResponseEntity) Reset() {
	*x = EncodeBatchLinksResponseEntity{}
	mi := &file_api_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeBatchLinksResponseEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeBatchLinksResponseEntity) ProtoMessage() {}

func (x *EncodeBatchLinksResponseEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeBatchLinksResponseEntity.ProtoReflect.Descriptor instead.
func (*EncodeBatchLinksResponseEntity) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *EncodeBatchLinksResponseEntity) GetCorrelationID() string {
	if x != nil {
		return x.CorrelationID
	}
	return ""
}

func (x *EncodeBatchLinksResponseEntity) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

// ---------------- ссылки пользователя -------------------------------
// UserLinksRequest запрос всех ссылок пользователя
type UserLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserLinksRequest) Reset() {
	*x = UserLinksRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinksRequest) ProtoMessage() {}

func (x *UserLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinksRequest.ProtoReflect.Descriptor instead.
func (*UserLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{10}
}

// UserLinksResponse ответ на запрос всех сокращенных ссылок пользователя
type UserLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link []*UserLinksResponseEntity `protobuf:"bytes,2,rep,name=link,proto3" json:"link,omitempty"` // массив с данными по сокращенным ссылка пользователя
}

func (x *UserLinksResponse) Reset() {
	*x = UserLinksResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinksResponse) ProtoMessage() {}

func (x *UserLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinksResponse.ProtoReflect.Descriptor instead.
func (*UserLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *UserLinksResponse) GetLink() []*UserLinksResponseEntity {
	if x != nil {
		return x.Link
	}
	return nil
}

// UserLinksResponseEntity содержание записи ответа на запрос всех сокращенных ссылок пользователя
type UserLinksResponseEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortURL    string `protobuf:"bytes,1,opt,name=ShortURL,proto3" json:"ShortURL,omitempty"`       // коротка ссылка
	OriginalURL string `protobuf:"bytes,2,opt,name=OriginalURL,proto3" json:"OriginalURL,omitempty"` // оригинальный адрес
}

func (x *UserLinksResponseEntity) Reset() {
	*x = UserLinksResponseEntity{}
	mi := &file_api_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinksResponseEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinksResponseEntity) ProtoMessage() {}

func (x *UserLinksResponseEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinksResponseEntity.ProtoReflect.Descriptor instead.
func (*UserLinksResponseEntity) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *UserLinksResponseEntity) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *UserLinksResponseEntity) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

// ---------------- удаление ссылок пользователя ----------------------
// DeleteUserLinksRequest запрос на удаление ссылок пользователя с токеном в контексте
type DeleteUserLinksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short []string `protobuf:"bytes,2,rep,name=Short,proto3" json:"Short,omitempty"` // массив с хешами сокращенных ссылок
}

func (x *DeleteUserLinksRequest) Reset() {
	*x = DeleteUserLinksRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserLinksRequest) ProtoMessage() {}

func (x *DeleteUserLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserLinksRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserLinksRequest) GetShort() []string {
	if x != nil {
		return x.Short
	}
	return nil
}

// DeleteUserLinksResponse ответ на запрос удаления ссылок пользователя
type DeleteUserLinksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode uint32 `protobuf:"varint,1,opt,name=ResultCode,proto3" json:"ResultCode,omitempty"` // код результата операции
}

func (x *DeleteUserLinksResponse) Reset() {
	*x = DeleteUserLinksResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserLinksResponse) ProtoMessage() {}

func (x *DeleteUserLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserLinksResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserLinksResponse) GetResultCode() uint32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

// ---------------- статистика сервера -------------------------------
// InternalStatsRequest запрос статистики сервера
type InternalStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InternalStatsRequest) Reset() {
	*x = InternalStatsRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalStatsRequest) ProtoMessage() {}

func (x *InternalStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalStatsRequest.ProtoReflect.Descriptor instead.
func (*InternalStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{15}
}

// InternalStatusResponse ответ на запрос статистики сервера
type InternalStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  uint64 `protobuf:"varint,1,opt,name=Urls,proto3" json:"Urls,omitempty"`
	Users uint64 `protobuf:"varint,2,opt,name=Users,proto3" json:"Users,omitempty"`
}

func (x *InternalStatsResponse) Reset() {
	*x = InternalStatsResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalStatsResponse) ProtoMessage() {}

func (x *InternalStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalStatsResponse.ProtoReflect.Descriptor instead.
func (*InternalStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *InternalStatsResponse) GetUrls() uint64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *InternalStatsResponse) GetUsers() uint64 {
	if x != nil {
		return x.Users
	}
	return 0
}

// ---------------- проверка соединения с бд -------------------------
// DBPingRequest запрос проверки соединения с БД
type DBPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DBPingRequest) Reset() {
	*x = DBPingRequest{}
	mi := &file_api_proto_shortener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBPingRequest) ProtoMessage() {}

func (x *DBPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBPingRequest.ProtoReflect.Descriptor instead.
func (*DBPingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{17}
}

// DBPingResponse ответ на запрос проверки статуса БД
type DBPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode uint32 `protobuf:"varint,1,opt,name=ResultCode,proto3" json:"ResultCode,omitempty"` // код результата операции
}

func (x *DBPingResponse) Reset() {
	*x = DBPingResponse{}
	mi := &file_api_proto_shortener_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBPingResponse) ProtoMessage() {}

func (x *DBPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_shortener_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBPingResponse.ProtoReflect.Descriptor instead.
func (*DBPingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_shortener_proto_rawDescGZIP(), []int{18}
}

func (x *DBPingResponse) GetResultCode() uint32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

var File_api_proto_shortener_proto protoreflect.FileDescriptor

var file_api_proto_shortener_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x43, 0x0a, 0x13, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x22, 0x2c, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3f,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22,
	0x28, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x35, 0x0a, 0x11, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x22, 0x32, 0x0a, 0x12, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x5e, 0x0a, 0x17, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x43, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x22, 0x67, 0x0a, 0x1d, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f,
	0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x4f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x22, 0x5e, 0x0a,
	0x18, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x04, 0x4c, 0x69, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x62, 0x0a,
	0x1e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x57, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x20,
	0x0a, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x52, 0x4c,
	0x22, 0x2e, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x22, 0x39, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x55, 0x72, 0x6c, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x42, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x0e, 0x44, 0x42, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x32, 0xd1, 0x05, 0x0a, 0x0d, 0x47, 0x72,
	0x70, 0x63, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x59, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75,
	0x74, 0x68, 0x12, 0x1f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0a, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x0f, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x27, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x50, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x20, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x62, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x26, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x44, 0x42, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1d,
	0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x44, 0x42, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x42, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a,
	0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_shortener_proto_rawDescOnce sync.Once
	file_api_proto_shortener_proto_rawDescData = file_api_proto_shortener_proto_rawDesc
)

func file_api_proto_shortener_proto_rawDescGZIP() []byte {
	file_api_proto_shortener_proto_rawDescOnce.Do(func() {
		file_api_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_shortener_proto_rawDescData)
	})
	return file_api_proto_shortener_proto_rawDescData
}

var file_api_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_shortener_proto_goTypes = []any{
	(*UserRegisterRequest)(nil),            // 0: shortener_grpc.UserRegisterRequest
	(*UserRegisterResponse)(nil),           // 1: shortener_grpc.UserRegisterResponse
	(*UserAuthRequest)(nil),                // 2: shortener_grpc.UserAuthRequest
	(*UserAuthResponse)(nil),               // 3: shortener_grpc.UserAuthResponse
	(*EncodeLinkRequest)(nil),              // 4: shortener_grpc.EncodeLinkRequest
	(*EncodeLinkResponse)(nil),             // 5: shortener_grpc.EncodeLinkResponse
	(*EncodeBatchLinksRequest)(nil),        // 6: shortener_grpc.EncodeBatchLinksRequest
	(*EncodeBatchLinksRequestEntity)(nil),  // 7: shortener_grpc.EncodeBatchLinksRequestEntity
	(*EncodeBatchLinksResponse)(nil),       // 8: shortener_grpc.EncodeBatchLinksResponse
	(*EncodeBatchLinksResponseEntity)(nil), // 9: shortener_grpc.EncodeBatchLinksResponseEntity
	(*UserLinksRequest)(nil),               // 10: shortener_grpc.UserLinksRequest
	(*UserLinksResponse)(nil),              // 11: shortener_grpc.UserLinksResponse
	(*UserLinksResponseEntity)(nil),        // 12: shortener_grpc.UserLinksResponseEntity
	(*DeleteUserLinksRequest)(nil),         // 13: shortener_grpc.DeleteUserLinksRequest
	(*DeleteUserLinksResponse)(nil),        // 14: shortener_grpc.DeleteUserLinksResponse
	(*InternalStatsRequest)(nil),           // 15: shortener_grpc.InternalStatsRequest
	(*InternalStatsResponse)(nil),          // 16: shortener_grpc.InternalStatsResponse
	(*DBPingRequest)(nil),                  // 17: shortener_grpc.DBPingRequest
	(*DBPingResponse)(nil),                 // 18: shortener_grpc.DBPingResponse
}
var file_api_proto_shortener_proto_depIdxs = []int32{
	7,  // 0: shortener_grpc.EncodeBatchLinksRequest.Links:type_name -> shortener_grpc.EncodeBatchLinksRequestEntity
	9,  // 1: shortener_grpc.EncodeBatchLinksResponse.Link:type_name -> shortener_grpc.EncodeBatchLinksResponseEntity
	12, // 2: shortener_grpc.UserLinksResponse.link:type_name -> shortener_grpc.UserLinksResponseEntity
	0,  // 3: shortener_grpc.GrpcShortener.UserRegister:input_type -> shortener_grpc.UserRegisterRequest
	2,  // 4: shortener_grpc.GrpcShortener.UserAuth:input_type -> shortener_grpc.UserAuthRequest
	4,  // 5: shortener_grpc.GrpcShortener.EncodeLink:input_type -> shortener_grpc.EncodeLinkRequest
	6,  // 6: shortener_grpc.GrpcShortener.BatchEncodeLink:input_type -> shortener_grpc.EncodeBatchLinksRequest
	10, // 7: shortener_grpc.GrpcShortener.UserLinks:input_type -> shortener_grpc.UserLinksRequest
	13, // 8: shortener_grpc.GrpcShortener.DeleteUserLinks:input_type -> shortener_grpc.DeleteUserLinksRequest
	15, // 9: shortener_grpc.GrpcShortener.InternalStats:input_type -> shortener_grpc.InternalStatsRequest
	17, // 10: shortener_grpc.GrpcShortener.DBPing:input_type -> shortener_grpc.DBPingRequest
	1,  // 11: shortener_grpc.GrpcShortener.UserRegister:output_type -> shortener_grpc.UserRegisterResponse
	3,  // 12: shortener_grpc.GrpcShortener.UserAuth:output_type -> shortener_grpc.UserAuthResponse
	5,  // 13: shortener_grpc.GrpcShortener.EncodeLink:output_type -> shortener_grpc.EncodeLinkResponse
	8,  // 14: shortener_grpc.GrpcShortener.BatchEncodeLink:output_type -> shortener_grpc.EncodeBatchLinksResponse
	11, // 15: shortener_grpc.GrpcShortener.UserLinks:output_type -> shortener_grpc.UserLinksResponse
	14, // 16: shortener_grpc.GrpcShortener.DeleteUserLinks:output_type -> shortener_grpc.DeleteUserLinksResponse
	16, // 17: shortener_grpc.GrpcShortener.InternalStats:output_type -> shortener_grpc.InternalStatsResponse
	18, // 18: shortener_grpc.GrpcShortener.DBPing:output_type -> shortener_grpc.DBPingResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_shortener_proto_init() }
func file_api_proto_shortener_proto_init() {
	if File_api_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_shortener_proto_goTypes,
		DependencyIndexes: file_api_proto_shortener_proto_depIdxs,
		MessageInfos:      file_api_proto_shortener_proto_msgTypes,
	}.Build()
	File_api_proto_shortener_proto = out.File
	file_api_proto_shortener_proto_rawDesc = nil
	file_api_proto_shortener_proto_goTypes = nil
	file_api_proto_shortener_proto_depIdxs = nil
}
